# Parameters:
#   - role-arn -- IAM role with permissions to modify EBS volumes. Can be the same as for EBS CSI driver
                see https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
#   - namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-params-controller
  annotations:
    eks.amazonaws.com/role-arn: ${role_arn}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebs-params-controller-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebs-params-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebs-params-controller-role
subjects:
- kind: ServiceAccount
  name: ebs-params-controller
  namespace: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-params-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-params-controller
  template:
    metadata:
      name: ebs-params-controller
      labels:
        app: ebs-params-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9115"
    spec:
      serviceAccountName: ebs-params-controller
      containers:
      - name: controller
        image: altinity/ebs-params-controller:v0.3.0
        env:
        - name: LOG_TYPE
          value: text
